### ISSUE TITLE
Lips

### ISSUE THREAD

**Issue by jcubic** [dundalek/awesome-lisp-languages#12]
Not sure if it's qualify, but LIPS (stands for LIPS Is Pretty Simple) is simple scheme like lisp in JavaScript. Maybe it's not so know as BiwaScheme, but I think it much better integrate with JavaScript and it can also be used in Node. I'ts Type-S but not full scheme.

https://jcubic.github.io/lips/

**Comment by dundalek** [comment]
Cool project, thanks, added.
