### ISSUE TITLE
JSLisp

### ISSUE THREAD

**Issue by no-e-in** [dundalek/awesome-lisp-languages#19]
A lisp-2 common-lisp like (but not too much) compiler in javascript and an IDE (written in JSLisp)

https://github.com/6502/JSLisp
http://www.jslisp.org
https://www.youtube.com/watch?v=g2o5VKdQqZ4

**Comment by dundalek** [comment]
Hi, thanks for the suggestion. It does not look like JSLisp is being worked on too much? I am thinking maybe to be a bit pickier especially for JS implementations since there are already quite a few. Or perhaps have an additional archive section.

**Comment by no-e-in** [comment]
I reported JSLisp because it has:
-  some original aspects highlighted on the [site](http://www.jslisp.org);
- a GUI (some example: an interactive [3d Rubik cube](http://www.jslisp.org/jslisp.html?load=examples/3d.lisp), a [pie chart builder](http://www.jslisp.org/jslisp.html?load=examples/piechart.lisp), a [chess](http://www.jslisp.org/jslisp.html?load=examples/chessboard.lisp) playing program);
- an IDE (with function help).

**Comment by dundalek** [comment]
cool, added
