### ISSUE TITLE
Typing grid

### ISSUE THREAD

**Issue by amirouche** [dundalek/awesome-lisp-languages#21]
Quote from the current `README`:

> - Type-A: Plain mapping from s-expressions - no extra semantics
> - Type-B: Extra semantics
> - Type-C: Clojure-like - persistent data structures, namespaces and vars, protocols, etc.
> - Type-L: Common Lisp
> - Type-S: Scheme

That typing, for a seasoned lisper, it can make sense, but from an outsider point of view, it is way too much jargon. `Type-B` in particular, I am not sure what it means.

I do not have a definitive answer / pull-request to make. My current thought would be to have several dimensions, and avoid *calling names of an existing LISP* except when it is relevant to FFI or / and host. Maybe I missed something...

**Comment by dundalek** [comment]
That classification is a thing I made up out of thin air. The naming is inspired by Type-1 and Type-2 which are lisp terms, but it is different. It is not very strictly defined, it is more based on a "feel", but I find it useful to group the languages by.  Basically programming languages can be similar to each other by looks (syntax) or features (semantics).

Historically, lisp languages were either implementing or similar to Common Lisp or Scheme. In recent years Clojure has been gaining more popularity and many new languages inspired by it popped up forming another cluster. Then there is a cluster of source translations coined as Type-A, these are usually also referred as transpilers. Type-B is the hardest to define and most fuzzy group, basically it is a catch-all that does not fit into any other category.

But you are right, it could use few more sentences for description to make things clearer, I will see if I could write something up.

**Comment by dundalek** [comment]
Added some more details in https://github.com/dundalek/awesome-lisp-languages/commit/0521d856ec4587607c899385f4e3a583ed77a856, hope that explains it a bit better.

**Comment by amirouche** [comment]
LGTM!
