### ISSUE TITLE
Consider adding NewLisp

### ISSUE THREAD

**Issue by claytonaalves** [dundalek/awesome-lisp-languages#29]
[NewLisp](http://www.newlisp.org/) is a language that borrows concepts from Common Lisp as well as Scheme.

- tiny
- portable
- multiplatform (windows, linux, ...)
- can build standalone executables

I think it's a Type-B language.

**Comment by dundalek** [comment]
Thanks for the suggestion, but I think I am going to skip on this one. It seems a bit esoteric, the website contains many broken links and there does not seem to be a version-controlled source code repo.
