### ISSUE TITLE
Inclusion Consideration

### ISSUE THREAD

**Issue by chr1st0scli** [dundalek/awesome-lisp-languages#31]
Hello.

I am not sure if you are interested in smaller LISP "cousins", but I would like to let you know about a humble LISP implementation called RainLisp which can be found here: [https://github.com/chr1st0scli/RainLisp](https://github.com/chr1st0scli/RainLisp).

It's open source, it has many similarities to Scheme, it's interpreted and runs on the .NET framework.

Thank you.

**Comment by dundalek** [comment]
Hi, cool project! Added it in https://github.com/dundalek/awesome-lisp-languages/commit/47a47c470e12188fce35da4debce4e35c715a712

In the README you mention it can be used as DSL to integrate with .NET which sounds interesting. If I may suggest I think it would be great to add an example to docs showing how to do the integration.
