### ISSUE TITLE
Embeddable Common Lisp (ECL)

### ISSUE THREAD

**Issue by slburson** [dundalek/awesome-lisp-languages#6]
A Common Lisp implementation that compiles to C and can be linked into any C or C++ program.  More info: https://common-lisp.net/project/ecl/main.html

**Comment by slburson** [comment]
Oh, I see it's on the Cliki page you link to.  Still, given its close relationship with C/C++, perhaps it deserves explicit mention here.

**Comment by babelchips** [comment]
Yes it seemed odd that ECL was omitted.
